services:
  debezium:
    image: solace/solace-pubsub-connector-debezium:3.0.2
    platform: linux/amd64
    container_name: debezium
    hostname: debezium
    networks:
      - demo-net
    # ports:
    #   - 8085:8085
    #   - 8090:8090
    environment:
      - SOLACE_CONNECTOR_SECURITY_USERS_0_NAME=connector
      - SOLACE_CONNECTOR_SECURITY_USERS_0_PASSWORD=connector
    volumes:
      - ./config/:/app/external/spring/config/:ro
      - ./libs/:/app/external/libs/:ro
