# Network declaration is optional.  However, if removed, all referenced
# modules need to have the same modification.
networks:
  demo-net:
    name: demo-net
    external: false
    driver: bridge

include:
  - solace/docker-compose.yaml

  # # Distributed Tracing
  # - jaeger/docker-compose.yaml
  # - otel-collector/docker-compose.yaml
  # # Granfana
  # - grafana/docker-compose.yaml

  # # MinIO - S3 emulator
  # - minio/docker-compose.yaml

  # Redpanda
  - redpanda/docker-compose.yaml

  # Event-management Agent
  - ema/docker-compose.yaml

  # # Prometheus
  # - prometheus/docker-compose.yaml



  ##### Connectors #####

  # Connector - Debezium
  - connector/debezium/docker-compose.yaml

  # Connector - File
  - connector/file-source/docker-compose.yaml
  - connector/file-sink/docker-compose.yaml

  # Connector - File to Events
  - connector/file-to-events/docker-compose.yaml

  # # IBM MQ
  - connector/ibm-mq/docker-compose.yaml
  - ibm-mq/docker-compose.yaml

  # # TIBCO EMS
  - connector/tibco/docker-compose.yaml
  - tibco/docker-compose.yaml



  ##### Databases #####

  # # MS SQL Server
  - connector/mssql-writer/docker-compose.yaml
  - database/mssql/docker-compose.yaml
