solace-db-sql:
  bindings:
    output-0:
      producer:
        dbConnectorBlobEncoding: BASE64
        dbConnectorTimestampFormat: 'yyyy/dd/MM HH:mm:ss'
        dbMsgHeaderTimestampFormat: 'yyyy/dd/MM HH:mm:ss.SSS'
        entities:
          TRANS:
            jsonNodePrefix: null
            topicOperations:
              insert:
                topics: 
                  - acmebank/solace/core/deposit/v1/*/*/>                
                  - acmebank/solace/core/withdrawal/v1/*/*/>                
                sql: >
                     EXEC dbo.PutTrans @trans_num = :trans_num
                                     , @account_num = :account_num
                                     , @trans_type = :trans_type
                                     , @trans_amt = :trans_amt
                                     , @trans_ccy = :trans_ccy;
