solace-connector-mapper:
  mapper-metadata:
    source-schema-type: json
    target-schema-type: null
    encrypted: null
    escape-special-characters: true
    source-schema-name: null
    target-schema-name: null
  payload-mapper:
    mapper-order_num:
      source-xpath: order_num
      source-datatype: string
      target-xpath: ORDER_COPY/order_num
      target-datatype: int
    mapper-customer_num:
      source-xpath: customer_num
      source-datatype: string
      target-xpath: ORDER_COPY/customer_num
      target-datatype: int
    mapper-order_amt:
      source-xpath: order_amt
      source-datatype: string
      target-xpath: ORDER_COPY/order_amt
      target-datatype: numeric
    mapper-order_ccy:
      source-xpath: order_ccy
      source-datatype: string
      target-xpath: ORDER_COPY/order_ccy
      target-datatype: varchar
    mapper-created_dt:
      source-xpath: created_dt
      source-datatype: string
      target-xpath: ORDER_COPY/created_dt
      target-datatype: date
    mapper-last_modified_dt:
      source-xpath: last_modified_dt
      source-datatype: string
      target-xpath: ORDER_COPY/last_modified_dt
      target-datatype: date

#param1 should be the same as source-xpath value