services:
  connector-file-source:
    image: solace/solace-pubsub-connector-file:2.3.0
    platform: linux/amd64
    container_name: connector-file-source
    networks:
    - demo-net
    ports:
    - 8091:8090
    volumes:
    - ./config/:/app/external/spring/config
    - ./outgoing/:/outgoing
