const:
  - &solace tcp://solace:55555
  - &vpn default
  - &topic solace/fc/event
  - &conn-user connector
  - &conn-pwd connector
  - &cc-topic solace/dd/STORE-MANGEMENT/fa-segmenter/cc/se/fa/segmenter/Stockholm

server.port: 8090

spring:
  application:
    name: File to Events Connector
  cloud:
    stream:        
      bindings:
        input-0:
          destination: /app/external/spring/config/static.cfg
          binder: file
        output-0:
          destination: *topic
          binder: solace
        input-1:
          destination: /source/account-sample.csv
          # destination: /source/static.cfg
          binder: file
        output-1:
          destination: *topic
          binder: solace
        input-2:
          destination: /source/account-sample.csv
          binder: file
        output-2:
          destination: *topic
          binder: solace
        input-3:
          destination: /app/external/spring/config/directory-paths.cfg
          binder: file
        output-3:
          destination: *topic
          binder: solace

file:
  source:
    scheduler.restart_time_sec: 10
    general:
      adapter_id: SOURCE_CONN_ID1
      # 1 = static | 2 = dynamic | 3 = folder | 4 = folder & sub
      file_type: 2
      state_backup_path: /storage/backup_state.cfg
      copy_file_mode_permissions: 0
      max_file_transfer_size: 999000
      max_files_allowed: 99999
      max_bandwidth_limit: 0
      clear_state_on_eod: 0
      eod_time_sec: -1
    file_to_event:
      enabled: 1
      fileFormat: 1
      # eventDelimiter: '|' 
      paramDelimiter: ','
      dynamicTopic: solace/fc/event/dynamic/${param-1}/${Country}/${State}
      paramHeaderMap: type,AccountId,FirstName,LastName,FullName,State,Country,Status
      # jsonPath: '$.Authors[*].Books[*]'
      # xPath: '/class/student'
    sftp_settings:
      enabled: 0
      ip: SFTP_HOST_ADDRESS
      port: 22
      user: SFTP_USER
      password: SFTP_PASSWORD
      strictHostKeyChecking: no
      #privateKeyPath: /home/centos/.ssh/id_rsa
    ftp_settings:
      enabled: 0
      ip: FTP_HOST_ADDRESS
      port: 21
      user: FTP_USER
      password: FTP_PASSWORD
      secured: true
    directory_wildcard:
      wildcard_type: 0
      config_path: /app/external/spring/config/dir_regexps.conf
    directory_replication:
      start_time: -1
    solace_out:
      lvq: CONN-FILE-EVENTS-LVQ
      destination: *topic
    command_center:
      enabled: 0
      useOutputDestinationSolaceCredentials: true
      heartbeat_enabled: 0
      heartbeat_interval: 3
      solace_base_publish_topic: *cc-topic
      solace_base_publish_topic_heartbeat: *cc-topic
      solace_messaging_mode: PERSISTENT

solace:
  connector:
    error:
      handle: stop_all
    workflows:
      0:
        enabled: false
        acknowledgment.publish-async: true
      1:
        enabled: false
        acknowledgment.publish-async: true
      2: # transfer all files in a folder
        enabled: true
        acknowledgment.publish-async: true
      3: # transfer all files in a folder and sub folder
        enabled: false
        acknowledgment.publish-async: true
    management:
      leader-election:
        mode: standalone  # The connector’s leader election mode. (values: standalone, active_active, active_standby)
        fail-over:
          max-attempts: 3  # The maximum number of attempts to perform a fail-over.
          back-off-initial-interval: 1000  # The initial interval (milliseconds) to back-off when retrying a fail-over.
          back-off-max-interval: 10000  # The maximum interval (milliseconds) to back-off when retrying a fail-over.
          back-off-multiplier: 2.0  # The multiplier to apply to the back-off interval between each retry of a fail-over.
      queue: CONN-MGMT-FILE-SOURCE  # The management queue name.
      session: # The management session. This has the same interface as that used by `solace.java.*`. For more info: https://github.com/SolaceProducts/solace-spring-boot/tree/master/solace-spring-boot-starters/solace-java-spring-boot-starter#updating-your-application-properties
        host: *solace
        msg-vpn: *vpn
        client-username: *conn-user
        client-password: *conn-pwd
  java:
    host: *solace
    msg-vpn: *vpn
    client-username: *conn-user
    client-password: *conn-pwd
    connectRetries: -1
    reconnectRetries: -1

logging:  # Logging configuration. For more info: https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging
  level:
    root: WARN
    com.solace.connector.jms: INFO # Enables TRACE logs for connector
    com.solace.connector.core: INFO # Enables TRACE logs for connector framework
    com.solace.spring.cloud.stream.binder: INFO # Enables TRACE logs for Solace and JMS binders
    # com.solacecoe.spring.cloud.stream.binders.file: TRACE # Enables TRACE logs for Solace and JMS binders
  file:
    name: myapp.log  # base log file name
  logback:
    rollingpolicy:  # Logback file rolling policy
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz"  # Pattern for rolled-over log file names. Example: Rolls the log file into an archive once every day. `%i` is reset to `0` at the start of the day.
      max-file-size: 100MB  # The maximum size of log file before it is archived. Example: Within a given day, when the log file reaches 100 MB, archive it, and increment `%i`.
      max-history: 7  # The maximum rotation-period's worth of archive log files to keep. Example: Since the `file-name-pattern` is configured to rollover once every day, keep 7 days worth of log archives.
      total-size-cap: 1GB  # Total size of log backups for a given rotation period. Example: Keep up-to 1 GB of log archives for every day.

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    logfile:
      external-file: myapp.log
    prometheus:
      enabled: false
    health:
      show-details: ALWAYS
      status:
        # Change default order so that RECONNECTING takes precedence over UP and UNKNOWN
        order:
          - DOWN
          - OUT_OF_SERVICE
          - RECONNECTING
          - UP
          - UNKNOWN
