services:
  connector-file-sink:
    image: solace/solace-pubsub-connector-file:2.3.0
    platform: linux/amd64
    container_name: connector-file-sink
    networks:
    - demo-net
    ports:
    - 8092:8090
    volumes:
    - ./config/:/app/external/spring/config
    - ./incoming/:/incoming
