springdoc:
  packages-to-scan: com.solace.maas.ep.event.management.agent.scanManager.rest
  api-docs:
    path: /docs/event-management-agent
  swagger-ui:
    path: /event-management-agent/swagger-ui.html
server:
  port: 8180
spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:5MB}
      max-request-size: ${MAX_REQUEST_SIZE:5MB}
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:file:./data/cache;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    driver-class-name: org.h2.Driver
    password: password
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2
  main:
    allow-bean-definition-overriding: true
camel:
  springboot:
    use-mdc-logging: true
kafka:
  client:
    config:
      reconnections:
        max-backoff:
          value: 1000
          unit: milliseconds
        backoff:
          value: 50
          unit: milliseconds
      connections:
        max-idle:
          value: 10000
          unit: milliseconds
        request-timeout:
          value: 5000
          unit: milliseconds
        timeout:
          value: 60000
          unit: milliseconds
eventPortal:
  organizationId: ${EP_ORGANIZATION_ID:uhgkb03281e}
  runtimeAgentId: ${EP_RUNTIME_AGENT_ID:1uhk73mak26}
  gateway:
    id: g527g4hnak7
    name: US East EVMR
    messaging:
      standalone: false
      rtoSession: false
      enableHeartbeats: true
      testHeartbeats: true
      connections:
      - name: eventPortalGateway
        authenticationType: ${EP_GATEWAY_AUTH:basicAuthentication}
        msgVpn: ${EP_GATEWAY_MSGVPN:us-east-evmr}
        url: ${EP_GATEWAY_URL:tcps://mr-connection-f0uthnm4q94.messaging.solace.cloud:55443}
        users:
        - clientName: client_1uhk73mak26
          username: ${EP_GATEWAY_USERNAME:uhgkb03281e-naazw78r87r-1uhk73mak26}
          password: $1GjoQ4YFyopYf1-V}FWL^p6
          name: messaging1
  topicPrefix: ${EP_TOPIC_PREFIX:sc/ep/runtime}
