services:
  mssql-writer:
    image: pubsubplus-connector-database-sql:v1.0.0
    container_name: mssql-writer
    hostname: mssql-writer
    networks:
      - demo-net
    environment:
      - SOLACE_CONNECTOR_SECURITY_USERS_0_NAME=connector
      - SOLACE_CONNECTOR_SECURITY_USERS_0_PASSWORD=connector
    volumes:
      - ./config/:/config/:ro
      - ./libs/:/app/external/libs/:ro
