spring:
 boot:
  admin:
   client:
    instance:
     prefer-ip: true
     management-url: http://54.242.202.202:8083/actuator
     service-url: http://54.242.202.202:8083/
    enabled: true
    url: http://50.17.36.43:9500/admin
    auto-registration: true
    prefer-ip: true
    username: user
    password: pass
 application:
  name: File to File Connector(Sink)