services:
  connector-file-delta-source:
    image: 'solace/solace-pubsub-connector-file:2.2.0'
    container_name: connector-file-delta-source
    networks:
      - demo-net
    ports:
      - 8093:8090
    volumes:
      - ./config/:/app/external/spring/config
      - ./outgoing/:/outgoing
